/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as CampaignsRouteImport } from './routes/campaigns'
import { Route as CompaniesRouteImport } from './routes/companies'
import { Route as ContactsRouteImport } from './routes/contacts'
import { Route as DiscoveryRouteImport } from './routes/discovery'
import { Route as DraftsRouteImport } from './routes/drafts'
import { Route as MailboxRouteImport } from './routes/mailbox'
import { Route as ResearchQueueRouteImport } from './routes/research-queue'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as CompaniesCompanyIdRouteImport } from './routes/companies.$companyId'
import { Route as ContactsContactIdRouteImport } from './routes/contacts.$contactId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsRoute = CampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesRoute = CompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsRoute = ContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoveryRoute = DiscoveryRouteImport.update({
  id: '/discovery',
  path: '/discovery',
  getParentRoute: () => rootRouteImport,
} as any)
const DraftsRoute = DraftsRouteImport.update({
  id: '/drafts',
  path: '/drafts',
  getParentRoute: () => rootRouteImport,
} as any)
const MailboxRoute = MailboxRouteImport.update({
  id: '/mailbox',
  path: '/mailbox',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchQueueRoute = ResearchQueueRouteImport.update({
  id: '/research-queue',
  path: '/research-queue',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesCompanyIdRoute = CompaniesCompanyIdRouteImport.update({
  id: '/$companyId',
  path: '/$companyId',
  getParentRoute: () => CompaniesRoute,
} as any)
const ContactsContactIdRoute = ContactsContactIdRouteImport.update({
  id: '/$contactId',
  path: '/$contactId',
  getParentRoute: () => ContactsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/campaigns': typeof CampaignsRoute
  '/companies': typeof CompaniesRouteWithChildren
  '/contacts': typeof ContactsRouteWithChildren
  '/discovery': typeof DiscoveryRoute
  '/drafts': typeof DraftsRoute
  '/mailbox': typeof MailboxRoute
  '/research-queue': typeof ResearchQueueRoute
  '/settings': typeof SettingsRoute
  '/companies/$companyId': typeof CompaniesCompanyIdRoute
  '/contacts/$contactId': typeof ContactsContactIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/campaigns': typeof CampaignsRoute
  '/companies': typeof CompaniesRouteWithChildren
  '/contacts': typeof ContactsRouteWithChildren
  '/discovery': typeof DiscoveryRoute
  '/drafts': typeof DraftsRoute
  '/mailbox': typeof MailboxRoute
  '/research-queue': typeof ResearchQueueRoute
  '/settings': typeof SettingsRoute
  '/companies/$companyId': typeof CompaniesCompanyIdRoute
  '/contacts/$contactId': typeof ContactsContactIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/campaigns': typeof CampaignsRoute
  '/companies': typeof CompaniesRouteWithChildren
  '/contacts': typeof ContactsRouteWithChildren
  '/discovery': typeof DiscoveryRoute
  '/drafts': typeof DraftsRoute
  '/mailbox': typeof MailboxRoute
  '/research-queue': typeof ResearchQueueRoute
  '/settings': typeof SettingsRoute
  '/companies/$companyId': typeof CompaniesCompanyIdRoute
  '/contacts/$contactId': typeof ContactsContactIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/campaigns'
    | '/companies'
    | '/contacts'
    | '/discovery'
    | '/drafts'
    | '/mailbox'
    | '/research-queue'
    | '/settings'
    | '/companies/$companyId'
    | '/contacts/$contactId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/campaigns'
    | '/companies'
    | '/contacts'
    | '/discovery'
    | '/drafts'
    | '/mailbox'
    | '/research-queue'
    | '/settings'
    | '/companies/$companyId'
    | '/contacts/$contactId'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/campaigns'
    | '/companies'
    | '/contacts'
    | '/discovery'
    | '/drafts'
    | '/mailbox'
    | '/research-queue'
    | '/settings'
    | '/companies/$companyId'
    | '/contacts/$contactId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  CampaignsRoute: typeof CampaignsRoute
  CompaniesRoute: typeof CompaniesRouteWithChildren
  ContactsRoute: typeof ContactsRouteWithChildren
  DiscoveryRoute: typeof DiscoveryRoute
  DraftsRoute: typeof DraftsRoute
  MailboxRoute: typeof MailboxRoute
  ResearchQueueRoute: typeof ResearchQueueRoute
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns': {
      id: '/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof CampaignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies': {
      id: '/companies'
      path: '/companies'
      fullPath: '/companies'
      preLoaderRoute: typeof CompaniesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts': {
      id: '/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof ContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discovery': {
      id: '/discovery'
      path: '/discovery'
      fullPath: '/discovery'
      preLoaderRoute: typeof DiscoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drafts': {
      id: '/drafts'
      path: '/drafts'
      fullPath: '/drafts'
      preLoaderRoute: typeof DraftsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mailbox': {
      id: '/mailbox'
      path: '/mailbox'
      fullPath: '/mailbox'
      preLoaderRoute: typeof MailboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research-queue': {
      id: '/research-queue'
      path: '/research-queue'
      fullPath: '/research-queue'
      preLoaderRoute: typeof ResearchQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies/$companyId': {
      id: '/companies/$companyId'
      path: '/$companyId'
      fullPath: '/companies/$companyId'
      preLoaderRoute: typeof CompaniesCompanyIdRouteImport
      parentRoute: typeof CompaniesRoute
    }
    '/contacts/$contactId': {
      id: '/contacts/$contactId'
      path: '/$contactId'
      fullPath: '/contacts/$contactId'
      preLoaderRoute: typeof ContactsContactIdRouteImport
      parentRoute: typeof ContactsRoute
    }
  }
}

interface CompaniesRouteChildren {
  CompaniesCompanyIdRoute: typeof CompaniesCompanyIdRoute
}

const CompaniesRouteChildren: CompaniesRouteChildren = {
  CompaniesCompanyIdRoute: CompaniesCompanyIdRoute,
}

const CompaniesRouteWithChildren = CompaniesRoute._addFileChildren(
  CompaniesRouteChildren,
)

interface ContactsRouteChildren {
  ContactsContactIdRoute: typeof ContactsContactIdRoute
}

const ContactsRouteChildren: ContactsRouteChildren = {
  ContactsContactIdRoute: ContactsContactIdRoute,
}

const ContactsRouteWithChildren = ContactsRoute._addFileChildren(
  ContactsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  CampaignsRoute: CampaignsRoute,
  CompaniesRoute: CompaniesRouteWithChildren,
  ContactsRoute: ContactsRouteWithChildren,
  DiscoveryRoute: DiscoveryRoute,
  DraftsRoute: DraftsRoute,
  MailboxRoute: MailboxRoute,
  ResearchQueueRoute: ResearchQueueRoute,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
